// 은행 목록 (2자리 코드 사용) - 사용 빈도 순 정렬
export const BANK_LIST = [
  { code: "06", name: "KB국민은행" },
  { code: "88", name: "신한은행" },
  { code: "20", name: "우리은행" },
  { code: "81", name: "하나은행" },
  { code: "03", name: "IBK기업은행" },
  { code: "11", name: "NH농협은행" },
  { code: "07", name: "Sh수협은행" },
  { code: "90", name: "카카오뱅크" },
  { code: "89", name: "케이뱅크" },
  { code: "92", name: "토스뱅크" },
  { code: "71", name: "우체국예금보험" },
  { code: "45", name: "새마을금고" },
  { code: "32", name: "부산은행" },
  { code: "34", name: "광주은행" },
  { code: "39", name: "경남은행" },
  { code: "31", name: "iM뱅크(대구)" },
  { code: "37", name: "전북은행" },
  { code: "35", name: "제주은행" },
  { code: "27", name: "씨티은행" },
  { code: "23", name: "SC제일은행" },
  { code: "48", name: "신협" },
  { code: "50", name: "저축은행중앙회" },
  { code: "64", name: "산림조합" },
  { code: "12", name: "단위농협(지역농축협)" },
  { code: "02", name: "한국산업은행" },
  { code: "54", name: "홍콩상하이은행" },
];
